# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: DefaultAgentPool

variables:
  node.version: '20.x'
  app.location: '/'
  api.location: 'api'
  output.location: 'build'

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '$(node.version)'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build React app'

- script: |
    cd $(api.location)
    npm install
  displayName: 'Install API dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(app.location)'
    api_location: '$(api.location)'
    output_location: '$(output.location)'
    verbose: true
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
  displayName: 'Deploy to Azure Static Web App'

- script: |
    sudo chown -R $(id -u):$(id -g) $(Build.SourcesDirectory)
    sudo chmod -R 777 $(Build.SourcesDirectory)
  displayName: 'Set permissions for working directory'

